version: "3"
services:
        captainslog:
                build: .
                restart: always
                container_name: captainslog
                hostname: 'blog.philgore.net'
                volumes:
                        - '/opt/blog:/opt/blog'
                environment:
                        VIRTUAL_PORT: 8000
                        VIRTUAL_HOST: 'blog.philgore.net'
                        LETSENCRYPT_EMAIL: 'example@gmail.com'
                        LETSENCRYPT_HOST: 'blog.philgore.net'
                expose:
                        - 8000
networks:
    default:
      external:
        name: nginx-net
