version: "3"
services:
        shoutcast:
                build: .
                restart: always
                container_name: shoutcast_server
                hostname: 'shoutcast.philgore.net'
                environment: 
                        VIRTUAL_HOST: 'radio.philgore.net'
                        VIRTUAL_PORT: 8000
                        LETSENCRYPT_EMAIL: 'example@gmail.com'
                        LETSENCRYPT_HOST: 'radio.philgore.net'
                expose:
                        - 80
                        - 8001
                        - 8000
networks:
        default:
                external:
                        name: nginx-net
