version: "3"
services:
    gitlab:
        image: 'gitlab/gitlab-ce:latest'
        restart: always
        container_name: gitlab
        hostname: 'git.philgore.net'
        environment:
            GITLAB_OMNIBUS_CONFIG:
                external_url 'https://git.philgore.net'
            VIRTUAL_HOST: 'git.philgore.net'
            LETSENCRYPT_EMAIL: 'example@gmail.com'
            LETSENCRYPT_HOST: 'git.philgore.net' 
        expose:
            - 80
            - 443
        ports:
            - '44:22'
        volumes:
            - '/srv/gitlab/config:/etc/gitlab'
            - '/srv/gitlab/logs:/var/log/gitlab'
            - '/srv/gitlab/data:/var/opt/gitlab'

networks:
    default:
        external:
            name: nginx-net 
